apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${DEPLOYMENT_WEB@microservice-auth-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: '${DEPLOYMENT_WEB@microservice-auth-config}'
    moduleid: microservice-auth-web-service
    version: 1.70.2-web-auth-home-config-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '${DEPLOYMENT_WEB@microservice-auth-config}'
  template:
    metadata:
      labels:
        app: '${DEPLOYMENT_WEB@microservice-auth-config}'
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-auth-web-container:1.70.1-web-auth-home-config-prod'
          env:
            -
              name: HOST
              value: '${HOST@microservice-config}'
            -
              name: AUTH_BASE_ROUTE_APP
              value: '${BASE_ROUTE_APP@microservice-auth-config}'
            -
              name: AUTH_INTERNAL_PORT_APP
              value: '${INTERNAL_PORT_APP@microservice-auth-config}'
            -
              name: AUTH_EXTERNAL_URL_GRAPH
              value: 'http://${EXTERNAL_URL_GRAPH@microservice-auth-config}'
            -
              name: AUTH_INTERNAL_URL_GRAPH
              value: 'http://${INTERNAL_URL_GRAPH@microservice-auth-config}'
            -
              name: RESOURCE_BASE_ROUTE
              value: '${BASE_ROUTE@microservice-resources-config}'
          ports:
            -
              containerPort: '${INTERNAL_PORT_APP@microservice-auth-config}'
