apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-auth-web-deployment
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: microservice-auth-web-deployment
    moduleid: microservice-auth-web-service
    version: 1.70.1-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-auth-web-deployment
  template:
    metadata:
      labels:
        app: microservice-auth-web-deployment
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-auth-web-container:1.70.1-master'
          env:
            -
              name: HOST
              value: '${HOST@microservice-config}'
            -
              name: PATH_APP
              value: '${PATH_URL_APP@microservice-auth-config}'
            -
              name: PORT
              value: '${PORT_APP@microservice-auth-config}'
            -
              name: URL_GRAPH
              value: '${HOST@microservice-config}/${PATH_URL_GRAPH@microservice-auth-config}'
            -
              name: URL_EVENTS
              value: '${HOST@microservice-config}/${PATH_URL_EVENTS@microservice-auth-config}'


          ports:
            -
              containerPort: ${PORT_APP@microservice-auth-config}
