apiVersion: v1
kind: Service
metadata:
  name: '${SERVICE_WEB@microservice-auth-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-auth-web-service
    version: 1.70.1-web-auth-home-config-prod
spec:
  type: NodePort
  selector:
    app: '${DEPLOYMENT_WEB@microservice-auth-config}'
  ports:
    -
      name: microservice-auth-web-port
      port: '${INTERNAL_PORT_APP@microservice-auth-config}'
