apiVersion: v1
kind: Service
metadata:
  name: microservice-auth-web-service
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-auth-web-service
    version: 1.70.1-master
spec:
  type: NodePort
  selector:
    app: microservice-auth-web-deployment
  ports:
    -
      name: microservice-auth-web-port
      port: ${PORT_APP@microservice-auth-config}
